services:
  - type: web
    name: luxnest-web
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: CLOUDINARY_URL
        sync: false
