const express = require('express');
const router = express.Router();
const Listing = require('../models/Listing');
const Review = require('../models/Review');
const User = require('../models/User');

const luxurySeedData = [
  {
    title: 'Villa Azure: Cliffside Infinity Pool & Sunset Panorama',
    description: 'Perched high above the Aegean Sea in Oia, Santorini, Villa Azure is an ultra-luxury sanctuary featuring a private heated infinity pool, panoramic caldera views, bespoke minimalist Cycladic architecture, private chef service on demand, and sunset vistas that will take your breath away.',
    images: [
      { url: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 850,
    location: 'Santorini, Cyclades',
    country: 'Greece',
    geometry: { type: 'Point', coordinates: [25.3753, 36.4618] },
    category: 'Amazing Pools',
    propertyType: 'Villa',
    amenities: ['Infinity Pool', 'Fast Wifi', 'Sea View', 'Air Conditioning', 'Hot Tub', 'Breakfast Included', 'Dedicated Workspace', 'Private Chef', 'Wine Cellar'],
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 3,
    cleaningFee: 90,
    serviceFee: 65,
    isGuestFavorite: true,
    rating: 4.98,
    reviewCount: 42,
  },
  {
    title: 'The Glass Horizon: Architectural Beachfront Oasis',
    description: 'Direct beachfront estate situated on the exclusive Carbon Beach in Malibu. Floor-to-ceiling retractable glass walls dissolve the boundary between luxury living and the Pacific Ocean. Fall asleep to crashing waves and unwind on your private teak ocean sundeck.',
    images: [
      { url: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1507652313519-d4e9174996dd?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 1250,
    location: 'Malibu, California',
    country: 'United States',
    geometry: { type: 'Point', coordinates: [-118.6826, 34.0381] },
    category: 'Beachfront',
    propertyType: 'House',
    amenities: ['Private Beach Access', 'Fast Wifi', 'Chef Kitchen', 'Hot Tub', 'EV Charger', 'Free Parking', 'BBQ Grill', 'Air Conditioning', 'Indoor Fireplace'],
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 4,
    cleaningFee: 150,
    serviceFee: 95,
    isGuestFavorite: true,
    rating: 4.96,
    reviewCount: 68,
  },
  {
    title: 'Chalet Mont Blanc: Alpine Luxury & Ski-in/Ski-out',
    description: 'Nestled in the French Alps with direct access to pristine powder slopes, this handcrafted timber and stone chalet blends rustic warmth with modern luxury. Features a private cedar barrel sauna, outdoor whirlpool facing snowcapped peaks, and an open hearth fireplace.',
    images: [
      { url: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1510798831971-661eb04b3739?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 950,
    location: 'Chamonix-Mont-Blanc',
    country: 'France',
    geometry: { type: 'Point', coordinates: [6.8694, 45.9237] },
    category: 'Ski-in/out',
    propertyType: 'Cabin',
    amenities: ['Ski-in/Ski-out', 'Cedar Sauna', 'Outdoor Hot Tub', 'Indoor Fireplace', 'Fast Wifi', 'Heated Floors', 'Ski Locker', 'Mountain View'],
    maxGuests: 10,
    bedrooms: 5,
    beds: 6,
    bathrooms: 4,
    cleaningFee: 120,
    serviceFee: 80,
    isGuestFavorite: true,
    rating: 4.99,
    reviewCount: 54,
  },
  {
    title: 'Bamboo Sanctuary: Eco-Luxe Treehouse Villa',
    description: 'Immerse yourself in Bali’s sacred Ayung River valley. Crafted entirely from sustainably harvested bamboo by master artisans, this multi-level architectural masterpiece offers an open-air living space, natural freshwater plunge pool, and lush jungle canopy views.',
    images: [
      { url: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 480,
    location: 'Ubud, Bali',
    country: 'Indonesia',
    geometry: { type: 'Point', coordinates: [115.2625, -8.5069] },
    category: 'Treehouses',
    propertyType: 'Treehouse',
    amenities: ['Plunge Pool', 'Jungle View', 'Fast Wifi', 'Yoga Deck', 'Daily Breakfast', 'Organic Garden', 'Spa Services'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    cleaningFee: 40,
    serviceFee: 35,
    isGuestFavorite: true,
    rating: 4.94,
    reviewCount: 91,
  },
  {
    title: 'Palazzo Bellagio: Lake Como Historic Grand Villa',
    description: 'Experience timeless Italian aristocracy on the tranquil waters of Lake Como. This 18th-century neoclassical villa boasts private boat dock access, frescoed ceilings, expansive botanical gardens, private marble baths, and Michelin-star private dining arrangements.',
    images: [
      { url: 'https://images.unsplash.com/photo-1533105079780-92b9be482077?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80' },
      { url: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 1800,
    location: 'Lake Como, Lombardy',
    country: 'Italy',
    geometry: { type: 'Point', coordinates: [9.2629, 45.9873] },
    category: 'Mansions',
    propertyType: 'Villa',
    amenities: ['Private Boat Dock', 'Lake View', 'Swimming Pool', 'Botanical Gardens', 'Fast Wifi', 'Concierge Service', 'Air Conditioning', 'Wine Cellar'],
    maxGuests: 12,
    bedrooms: 6,
    beds: 7,
    bathrooms: 6,
    cleaningFee: 200,
    serviceFee: 140,
    isGuestFavorite: true,
    rating: 4.97,
    reviewCount: 38,
  },
  {
    title: 'Aurora Glass Igloo & Nordic Spa Lodge',
    description: 'Watch the vibrant Aurora Borealis dancing across the Arctic sky from the comfort of your heated glass-dome master bedroom. Features an authentic wood-fired Finnish sauna, ice plunge bath, reindeer sleigh tours, and snowshoe trails directly outside your door.',
    images: [
      { url: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 720,
    location: 'Rovaniemi, Lapland',
    country: 'Finland',
    geometry: { type: 'Point', coordinates: [25.7289, 66.5039] },
    category: 'Arctic',
    propertyType: 'Cabin',
    amenities: ['Glass Roof', 'Wood-Fired Sauna', 'Heated Floors', 'Fireplace', 'Fast Wifi', 'Free Parking', 'Snow Gear Included'],
    maxGuests: 3,
    bedrooms: 1,
    beds: 2,
    bathrooms: 1,
    cleaningFee: 50,
    serviceFee: 45,
    isGuestFavorite: true,
    rating: 4.99,
    reviewCount: 115,
  },
  {
    title: 'The Royal Penthouse over Eiffel Tower & Seine',
    description: 'Spectacular duplex penthouse in the 7th arrondissement featuring a 360-degree wraparound terrace looking straight into the Eiffel Tower. Handcrafted herringbone parquet floors, Boffi gourmet kitchen, and bespoke Parisian art collection.',
    images: [
      { url: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 1100,
    location: 'Paris, Île-de-France',
    country: 'France',
    geometry: { type: 'Point', coordinates: [2.2945, 48.8584] },
    category: 'Iconic Cities',
    propertyType: 'Apartment',
    amenities: ['Eiffel Tower View', 'Wraparound Terrace', 'Fast Wifi', 'Elevator', 'Air Conditioning', 'Nespresso Bar', 'Concierge Service'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    cleaningFee: 110,
    serviceFee: 85,
    isGuestFavorite: true,
    rating: 4.95,
    reviewCount: 77,
  },
  {
    title: 'Dune Mirage: Stargazer Desert Villa & Private Oasis',
    description: 'Set amidst the dramatic red rock canyons and sculpted sands of Joshua Tree, Dune Mirage is an architectural marvel of mirrored glass and corten steel. Complete with private saltwater pool, cedar hot tub, telescope observation deck, and sunken fire lounge.',
    images: [
      { url: 'https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 640,
    location: 'Joshua Tree, California',
    country: 'United States',
    geometry: { type: 'Point', coordinates: [-116.3131, 34.1347] },
    category: 'Desert',
    propertyType: 'House',
    amenities: ['Saltwater Pool', 'Stargazing Telescope', 'Hot Tub', 'Fire Pit', 'Fast Wifi', 'EV Charger', 'Outdoor Shower', 'BBQ Grill'],
    maxGuests: 6,
    bedrooms: 3,
    beds: 3,
    bathrooms: 2,
    cleaningFee: 75,
    serviceFee: 50,
    isGuestFavorite: true,
    rating: 4.93,
    reviewCount: 63,
  },
  {
    title: 'Highland Castle of Inverness: 16th Century Royal Estate',
    description: 'Live like royalty in a meticulously restored 16th-century Scottish Baronial castle. Set on 500 acres of private ancient woodland with roaring stone fireplaces, grand banquet hall, whisky tasting salon, private loch access, and highland stag sightings.',
    images: [
      { url: 'https://images.unsplash.com/photo-1585543805890-6051f7829f98?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 1650,
    location: 'Inverness, Scottish Highlands',
    country: 'United Kingdom',
    geometry: { type: 'Point', coordinates: [-4.2247, 57.4778] },
    category: 'Castles',
    propertyType: 'Mansion',
    amenities: ['Private Estate', 'Grand Fireplaces', 'Whisky Tasting Room', 'Loch Access', 'Fast Wifi', 'Free Parking', 'Chef Kitchen', 'Billiards Room'],
    maxGuests: 16,
    bedrooms: 8,
    beds: 10,
    bathrooms: 8,
    cleaningFee: 250,
    serviceFee: 150,
    isGuestFavorite: true,
    rating: 4.98,
    reviewCount: 29,
  },
  {
    title: 'Overwater Coral Villa: Turquoise Lagoon Escape',
    description: 'Suspended directly above the crystal-clear turquoise waters of Bora Bora’s lagoon, this overwater bungalow features a glass floor viewing panel, private sundeck with stairs directly into coral reefs, outdoor soaking tub, and room service delivered by outrigger canoe.',
    images: [
      { url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 1400,
    location: 'Bora Bora',
    country: 'French Polynesia',
    geometry: { type: 'Point', coordinates: [-151.7415, -16.5004] },
    category: 'Islands',
    propertyType: 'Resort',
    amenities: ['Lagoon Access', 'Glass Floor', 'Snorkeling Gear', 'Air Conditioning', 'Fast Wifi', 'Spa Bathtub', 'Breakfast by Canoe'],
    maxGuests: 2,
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    cleaningFee: 80,
    serviceFee: 90,
    isGuestFavorite: true,
    rating: 4.99,
    reviewCount: 88,
  },
  {
    title: 'Tuscan Sun Estate: Olive Groves & Vineyard Villa',
    description: 'Surrounded by century-old olive groves and rolling Chianti vineyards in the heart of Florence countryside. Features a private stone pizza oven, zero-edge pool overlooking the hills, terracotta sun terraces, and authentic wine tasting cellar.',
    images: [
      { url: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 780,
    location: 'Florence, Tuscany',
    country: 'Italy',
    geometry: { type: 'Point', coordinates: [11.2558, 43.7696] },
    category: 'Countryside',
    propertyType: 'Villa',
    amenities: ['Private Pool', 'Vineyard View', 'Wood Pizza Oven', 'Wine Cellar', 'Fast Wifi', 'Free Parking', 'Chef Kitchen', 'Pet Friendly'],
    maxGuests: 8,
    bedrooms: 4,
    beds: 5,
    bathrooms: 3,
    cleaningFee: 85,
    serviceFee: 60,
    isGuestFavorite: true,
    rating: 4.97,
    reviewCount: 47,
  },
  {
    title: 'Kyoto Machiya Zen Retreat: Private Bamboo Garden & Onsen',
    description: 'An authentic 120-year-old traditional Machiya wooden townhouse lovingly renovated with modern luxury amenities in historic Gion. Features an aromatic Hinoki cypress soaking onsen tub, private rock garden, tatami tea ceremony room, and shoji screen architecture.',
    images: [
      { url: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80', isPrimary: true },
      { url: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80' },
    ],
    price: 520,
    location: 'Kyoto, Kansai',
    country: 'Japan',
    geometry: { type: 'Point', coordinates: [135.7681, 35.0116] },
    category: 'Trending',
    propertyType: 'House',
    amenities: ['Hinoki Onsen Tub', 'Private Zen Garden', 'Tea Ceremony Room', 'Fast Wifi', 'Heated Floors', 'Air Conditioning', 'Kimono Robes'],
    maxGuests: 4,
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    cleaningFee: 45,
    serviceFee: 40,
    isGuestFavorite: true,
    rating: 4.99,
    reviewCount: 104,
  },
];

router.post('/seed-data', async (req, res) => {
  try {
    const existingCount = await Listing.countDocuments();
    if (existingCount > 0) {
      await Listing.deleteMany({});
    }

    // Create default superhost user if none exists
    let host = await User.findOne({ email: 'superhost@luxnest.com' });
    if (!host) {
      host = await User.create({
        supabaseId: 'superhost-default-id-001',
        email: 'superhost@luxnest.com',
        name: 'Elena Rostova',
        avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
        bio: 'Superhost & luxury hospitality architect since 2018. Dedicated to curating unforgettable stays around the globe.',
        isSuperhost: true,
      });
    }

    const preparedListings = luxurySeedData.map((item) => ({
      ...item,
      owner: host._id,
    }));

    const inserted = await Listing.insertMany(preparedListings);

    // Add some sample reviews to the first listing
    const firstListing = inserted[0];
    const sampleReview = await Review.create({
      author: host._id,
      listing: firstListing._id,
      rating: 5,
      comment: 'An absolute masterpiece of a property. The sunset views over the caldera were the highlight of our European trip. Impeccable host and spotless amenities!',
      ratingsBreakdown: { cleanliness: 5, accuracy: 5, communication: 5, location: 5, checkIn: 5, value: 5 },
    });

    firstListing.reviews.push(sampleReview._id);
    await firstListing.save();

    res.status(200).json({
      success: true,
      message: `Successfully seeded ${inserted.length} luxury listings and host profile!`,
      count: inserted.length,
    });
  } catch (error) {
    console.error('Seeding error:', error);
    res.status(500).json({ success: false, message: error.message });
  }
});

module.exports = router;
